name: gitlab-runner
home: https://docs.gitlab.com/runner
icon: https://about.gitlab.com/images/default-blog-image.png
version: 0.0.1
appVersion: latest
description: 'run gitlab jobs'
keywords:
  - gitlab-runner
  - gitlab
  - runner
  - job
  - git
  - ci
sources:
  - https://gitlab.com/gitlab-org/gitlab-runner
maintainers:
  - name: 'Jam Risser'
    email: jam@codejam.ninja
