images:
  gitlabRunner:
    repository: gitlab/gitlab-runner
    tag: v12.1.0

config:
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  gitlab:
    baseUrl: ''
    ciToken: ''
  gitlabRunner:
    hostname: ''

service:
  gitlabRunner:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''

ingress:

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  backup:
    awsAccessKey: ''
    awsSecretKey: ''
    azureAccountKey: ''
    azureAccountName: ''
    bucket: ''
    container: ''
    enabled: false
    endpoint: s3.amazonaws.com
    googleProjectId: ''
    googleServiceKey: ''
    keepLast: 5
    prefix: ''
    resticPassword: pass
    restore:
      gitlabRunnerSnapshot: ''
    schedule: '@midnight'
    type: s3

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
