apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "wikijs.fullname" . }}-wikijs
  labels:
    app: {{ template "wikijs.name" . }}-wikijs
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "wikijs.name" . }}-wikijs
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "wikijs.fullname" . }}-wikijs
          image: {{ .Values.images.wikijs.repository }}:{{ .Values.images.wikijs.tag }}
          imagePullPolicy: {{ .Values.images.wikijs.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["cp /tmp/wiki/config.yml /var/wiki/config.yml && node server"]
          ports:
            - name: container
              containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /var/wiki/repo
              subPath: repo
            - name: data
              mountPath: /var/wiki/data
              subPath: data
            - name: config
              mountPath: /tmp/wiki
          env:
            - name: WIKI_ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "wikijs.fullname" . }}
                  key: email
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "wikijs.fullname" . }}-wikijs
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "wikijs.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
