apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "letsencrypt-cert.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: letsencrypt-staging
  issuerRef:
    name: {{ .Values.issuer.name }}
    kind: {{ .Values.issuer.kind }}
  commonName: '{{ .Values.domain }}'
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - '{{ .Values.domain }}'
