apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "gitlab-runner.fullname" . }}-gitlab-runner
  labels:
    app: {{ template "gitlab-runner.name" . }}-gitlab-runner
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "gitlab-runner.name" . }}-gitlab-runner
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        supplementalGroups: [999]
      containers:
        - name: {{ template "gitlab-runner.fullname" . }}-gitlab-runner
          image: {{ .Values.images.gitlab-runner.repository }}:{{ .Values.images.gitlab-runner.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 9100
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
          command:
            - /scripts/run.sh
          env:
            - name: REGISTER_NON_INTERACTIVE:
              value: 'true'
            - name: REGISTER_LOCKED
              value: 'false'
            - name: METRICS_SERVER
              value: '0.0.0.0:9100'
            - name: RUNNER_REQUEST_CONCURRENCY
              value: '4'
            - name: RUNNER_EXECUTOR
              value: kubernetes
            - name: KUBERNETES_PRIVILEGED
              value: 'true'
            - name: KUBERNETES_CPU_REQUEST
              value: '250m'
            - name: KUBERNETES_MEMORY_REQUEST
              value: '256Mi'
            - name: KUBERNETES_CPU_LIMIT
              value: '1'
            - name: KUBERNETES_MEMORY_LIMIT
              value: '1Gi'
            - name: KUBERNETES_SERVICE_CPU_REQUEST
              value: '150m'
            - name: KUBERNETES_SERVICE_MEMORY_REQUEST
              value: '256Mi'
            - name: KUBERNETES_SERVICE_CPU_LIMIT
              value: '1'
            - name: KUBERNETES_SERVICE_MEMORY_LIMIT
              value: '1Gi'
            - name: KUBERNETES_HELPER_CPU_REQUEST
              value: '150m'
            - name: KUBERNETES_HELPER_MEMORY_REQUEST
              value: '100Mi'
            - name: KUBERNETES_HELPER_CPU_LIMIT
              value: '500m'
            - name: KUBERNETES_HELPER_MEMORY_LIMIT
              value: '200Mi'
            - name: KUBERNETES_PULL_POLICY
              value: if-not-present
            - name: KUBERNETES_TERMINATIONGRACEPERIODSECONDS
              value: '10'
            - name: KUBERNETES_POLL_INTERVAL
              value: '5'
            - name: KUBERNETES_POLL_TIMEOUT
              value: '360'
            - name: KUBERNETES_NAMESPACE
              value: {{- .Release.Namespace }}
            - name: RUNNER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CI_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "gitlab-runner.fullname" . }}
                  key: gitlab_base_url
            - name: GITLAB_CI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "gitlab-runner.fullname" . }}
                  key: gitlab_ci_token
          livenessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
      volumes:
        - name: scripts
          configMap:
            name: {{ template "teleport.fullname" . }}-scripts
            items:
              - key: run.sh
                path: run.sh
                mode: 0755
