images:
  nextcloud:
    repository: nextcloud
    tag: 15.0.5-apache
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent

config:
  adminUser: 'admin'
  adminPassword: 'pass'
  postgres:
    database: nextcloud
    host: ''
    internal: true
    password: postgres
    username: postgres

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    nextcloud:
      http: ''

ingress:
  enabled: false
  tls: false
  certificate: ''
  issuer:
    name: letsencrypt-staging
  hosts:
    nextcloud:
      - name: ''
        path: /

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 10Gi
  storageClass: ''
  volbackBackup: false

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
