images:
    gitlab:
        repository: gitlab/gitlab-ce
        tag: 12.0.3-ce.0
        pullPolicy: IfNotPresent
    postgres:
        repository: postgres
        tag: latest
        pullPolicy: IfNotPresent
    redis:
        repository: redis
        tag: latest
        pullPolicy: IfNotPresent

config:
    password: password
    baseUrl: ''
    keycloak:
        baseUrl: ''
        clientId: ''
        companyName: KeyCloak
        enabled: false
        realmName: gatekeeper
        certificate: ''

    postgres:
        database: gitlab
        host: ''
        internal: true
        password: postgres
        port: 5432
        url: ''
        username: postgres
    redis:
        host: ''
        internal: true
        password: ''
        port: 6379
        url: ''
        username: ''

service:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
        gitlab:
            http: ''

ingress:
    enabled: false
    tls: false
    certificate: ''
    issuer:
        name: letsencrypt-staging
    hosts:
        gitlab:
            - name: ''
              path: /

persistence:
    accessMode: ReadWriteOnce
    enabled: false
    existingClaim: ''
    size: 10Gi
    storageClass: ''
    volbackBackup: false

probes:
    liveness:
        initialDelaySeconds: 120
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
    readiness:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
