apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "wikijs.fullname" . }}-wikijs
  labels:
    app: {{ template "wikijs.name" . }}-wikijs
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yml: |
    title: {{ .Values.config.title | quote }}
    host: {{ template "wikijs.base_url" . }}
    paths:
      repo: /var/wiki/repo
      data: /var/wiki/data
    lang: en
    langRtl: false
    public: false
    defaultReadAccess: false
    auth:
      local:
        enabled: true
    sessionSecret: 1234567890abcdefghijklmnopqrstuvxyz
    db: {{ template "wikijs.mongo_url" . }}
    git:
      url: {{ .Values.config.gitUrl | quote }}
      branch: master
      auth:
        type: basic
        username: {{ .Values.config.gitUsername | quote }}
        password: {{ .Values.config.gitPassword | quote }}
        sslVerify: true
      serverEmail: {{ .Values.config.email | quote }}
      showUserEmail: true
