apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "nextcloud.fullname" . }}-nextcloud
  labels:
    app: {{ template "nextcloud.name" . }}-nextcloud
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "nextcloud.name" . }}-nextcloud
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "nextcloud.fullname" . }}-nextcloud
          image: {{ .Values.images.nextcloud.repository }}:{{ .Values.images.nextcloud.tag }}
          imagePullPolicy: {{ .Values.images.nextcloud.pullPolicy }}
          ports:
            - name: container
              containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /var/www/html/data
              subPath: data
            - name: data
              mountPath: /var/www/html/apps
              subPath: apps
            - name: data
              mountPath: /var/www/html/themes
              subPath: themes
          env:
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: {{ (index .Values.ingress.hosts.nextcloud 0).name | quote }}
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: postgres_host
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: postgres_database
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: admin_user
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "nextcloud.fullname" . }}
                  key: admin_password
          livenessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "nextcloud.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
