apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "keycloak.fullname" . }}-keycloak
  labels:
    app: {{ template "keycloak.name" . }}-keycloak
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "keycloak.name" . }}-keycloak
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "keycloak.fullname" . }}-keycloak
          image: {{ .Values.images.keycloak.repository }}:{{ .Values.images.keycloak.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 8080
          env:
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_SCHEMA
              value: public
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'
            - name: DB_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ template "keycloak.fullname" . }}
                  key: postgres_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "keycloak.fullname" . }}
                  key: postgres_database
            {{- if .Values.config.postgres.internal }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "keycloak.sharedname" . }}-postgres-auth
                  key: POSTGRES_USER
            {{- else }}
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "keycloak.fullname" . }}
                  key: postgres_username
            {{- end }}
            - name: KEYCLOAK_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "keycloak.fullname" . }}
                  key: hostname
            - name: KEYCLOAK_LOGLEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "keycloak.fullname" . }}
                  key: loglevel
            - name: KEYCLOAK_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "keycloak.fullname" . }}
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "keycloak.fullname" . }}
                  key: password
            {{- if .Values.config.postgres.internal }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "keycloak.sharedname" . }}-postgres-auth
                  key: POSTGRES_PASSWORD
            {{- else }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "keycloak.fullname" . }}
                  key: postgres_password
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
