{{- if .Values.config.postgres.internal }}
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: {{ template "keycloak.fullname" . }}-postgres
  labels:
    app: {{ template "keycloak.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  version: {{ .Values.config.postgres.version | quote }}
  configSource:
    configMap:
      name: {{ template "keycloak.fullname" . }}-postgres
  standbyMode: {{ .Values.config.postgres.standbyMode | quote }}
  {{- if .Values.config.postgres.prometheus }}
  monitor:
    agent: prometheus.io/builtin
  {{- end }}
  {{- if (gt (.Values.config.postgres.replicas | int64) 1) }}
  replicas: {{ .Values.config.postgres.replicas }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storageType: Durable
  storage:
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ''
    {{- else }}
    storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    {{- end }}
    accessModes:
      - {{ .Values.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistence.size }}
  {{- else }}
  storageType: Ephemeral
  {{- end }}
  {{- if .Values.persistence.backup.enabled }}
  backupSchedule:
    cronExpression: {{ .Values.persistence.backup.schedule | quote }}
    storageSecretName: {{ template "keycloak.sharedname" . }}-backup
    {{ .Values.persistence.backup.type }}:
      {{- if (or (eq "gcs" .Values.persistence.backup.type) (eq "s3" .Values.persistence.backup.type)) }}
      bucket: {{ .Values.persistence.backup.bucket | quote }}
      {{- end }}
      {{- if (eq "s3" .Values.persistence.backup.type) }}
      endpoint: {{ .Values.persistence.backup.endpoint | quote }}
      {{- end }}
      {{- if (eq "azure" .Values.persistence.backup.type) }}
      container: {{ .Values.persistence.backup.container | quote }}
      {{- end }}
      prefix: {{ .Values.persistence.backup.prefix | quote }}
  {{- if (not (empty .Values.persistence.backup.restore.postgresSnapshot)) }}
  databaseSecret:
    {{- if (empty .Values.config.postgres.secret) }}
    secretName: {{ template "keycloak.sharedname" . }}-postgres-auth
    {{- else }}
    secretName: {{ .Values.config.postgres.secret }}
    {{- end }}
  init:
    snapshotSource:
      name: {{ .Values.persistence.backup.restore.postgresSnapshot }}
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
  {{- if (empty .Values.persistence.backup.restore.postgresSnapshot) }}
  init:
    scriptSource:
      configMap:
        name: {{ template "keycloak.fullname" . }}-postgres-init
  {{- end }}
  serviceTemplate:
    metadata:
      annotations:
        passMe: ToService
    spec:
      type: {{ .Values.service.postgres.type }}
      {{- if (or (eq .Values.service.postgres.type "LoadBalancer") (eq .Values.service.postgres.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.postgres.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: postgres
          port: 5432
          targetPort: postgres
          {{- if (and (eq .Values.service.postgres.type "NodePort") (not (empty .Values.service.postgres.nodePorts.postgres))) }}
          nodePort: {{ .Values.service.postgres.nodePorts.postgres }}
          {{- end }}
  replicaServiceTemplate:
    annotations:
      passMe: ToReplicaService
    spec:
      type: {{ .Values.service.postgres.type }}
      {{- if (or (eq .Values.service.postgres.type "LoadBalancer") (eq .Values.service.postgres.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.postgres.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: postgres
          port: 5432
          targetPort: postgres
          {{- if (and (eq .Values.service.postgres.type "NodePort") (not (empty .Values.service.postgres.nodePorts.postgres))) }}
          nodePort: {{ .Values.service.postgres.nodePorts.postgres }}
          {{- end }}
  updateStrategy:
    type: RollingUpdate
  {{- if .Values.persistence.enabled }}
  terminationPolicy: Pause
  {{- else }}
  terminationPolicy: Delete
  {{- end }}
{{- end }}
