images:
  gitlab:
    repository: gitlab/gitlab-ce
    tag: 12.0.3-ce.0
  pgadmin:
    repository: dpage/pgadmin4
    tag: 4.11
  phpredisadmin:
    repository: erikdubbelboer/phpredisadmin
    tag: v1.11.4

config:
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  password: password
  gitlab:
    baseUrl: ''
  keycloak:
    baseUrl: ''
    clientId: ''
    companyName: KeyCloak
    enabled: false
    realmName: gatekeeper
    certificate: ''
  pgadmin:
    email: admin
    enabled: false
    password: pass
  phpredisadmin:
    enabled: false
    password: pass
    username: admin
  postgres:
    customConfig: ''
    database: gitlab
    host: ''
    internal: true
    password: postgres
    port: 5432
    prometheus: false
    replicas: 1
    standbyMode: hot
    url: ''
    username: postgres
    version: 11.1
  redis:
    customConfig: ''
    host: ''
    internal: true
    password: ''
    port: 6379
    prometheus: false
    replicas: 1
    shards: 1
    url: ''
    username: ''
    version: 5.0.3-v1

service:
  gitlab:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''
  pgadmin:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''
  phpredisadmin:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''
  postgres:
    type: ClusterIP
    externalTrafficPolicy: Cluster
    nodePorts:
      postgres: ''
  redis:
    type: ClusterIP
    externalTrafficPolicy: Cluster
    nodePorts:
      redis: ''

ingress:
  gitlab:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging
  pgadmin:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging
  phpredisadmin:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  backup:
    awsAccessKey: ''
    awsSecretKey: ''
    azureAccountKey: ''
    azureAccountName: ''
    bucket: ''
    container: ''
    enabled: false
    endpoint: s3.amazonaws.com
    fullname: ''
    googleProjectId: ''
    googleServiceKey: ''
    keepLast: 5
    prefix: ''
    resticPassword: pass
    schedule: '@midnight'
    type: s3
    restore:
      gitlabSnapshot: ''
      postgresSnapshot: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
