images:
  jitsi:
    repository: jitsi
    tag: latest
    pullPolicy: IfNotPresent
  rocketchat:
    repository: rocket.chat
    tag: 0.69.1
    pullPolicy: IfNotPresent
  mongo:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent

config:
  base_url: ''
  mongo:
    database: wikijs
    host: ''
    internal: true
    password: ''
    port: 27017
    url: ''
    username: ''
  mail:
    smtp:
      host: ''
      port: 25
      username: ''
      password: ''
    from: ''
  jitsi:
    enabled: false
    domain: meet.jit.si
    url_room_prefix: RocketChat
    open_new_window: false
    enable_channels: false
    chrome_extension: ''
  webrtc:
    enable_channel: false
    enable_private: false
    enable_direct: false

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    rocketchat:
      http: ''
    jitsi:
      http: ''

ingress:
  enabled: false
  tls: false
  issuer:
    name: letsencrypt-staging
  hosts:
    rocketchat:
      - name: ''
        path: /
    jitsi:
      - name: ''
        path: /

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 10Gi
  storageClass: ''
  volbackBackup: false

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
