apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    app: {{ template "nextcloud.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  admin_password: {{ .Values.config.adminPassword | b64enc }}
  {{- $postgres := .Values.config.postgres }}
  postgres_password: {{ $postgres.password | b64enc }}
