images:
  sonarqube:
    repository: sonarqube
    tag: 7.7-community
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent

config:
  baseUrl: ''
  postgres:
    database: sonarqube
    host: ''
    internal: true
    password: postgres
    port: 5432
    url: ''
    username: postgres

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    sonarqube:
      http: ''

ingress:
  enabled: false
  tls: false
  issuer:
    name: letsencrypt-staging
  hosts:
    sonarqube:
      - name: ''
        path: /

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 10Gi
  storageClass: ''
  volbackBackup: false

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
