apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- $mysql := .Values.config.mysql }}
  mysql_url: {{ $mysql.url | b64enc }}
  mysql_password: {{ $mysql.password | b64enc }}
