{{- $mongo := .Values.config.mongo }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rocketchat.fullname" . }}
  labels:
    app: {{ template "rocketchat.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if (not (or $mongo.url $mongo.username $mongo.password)) }}
  {{- if $mongo.host }}
  mongo_url: mongodb://{{ $mongo.host }}:{{ $mongo.port }}/{{ $mongo.database }}
  {{- else }}
  mongo_url: mongodb://{{ template "rocketchat.fullname" . }}-mongo:27017/rocketchat
  {{- end }}
  {{- end }}
  {{- if .Values.config.base_url }}
  base_url: {{ .Values.config.base_url }}
  {{- else }}
  {{- if .Values.ingress.enabled }}
  {{- $host := (index .Values.ingress.hosts.rocketchat 0) }}
  {{- $protocol := "http" }}
  {{- if .Values.ingress.tls }}
  {{- $protocol := (printf "%ss" $protocol) }}
  {{- end }}
  base_url: {{ $protocol }}://{{ $host.name }}{{ $host.path }}
  {{- else }}
  base_url: http://{{ template "rocketchat.fullname" . }}-rocketchat
  {{- end }}
  {{- end }}
  mail_from: {{ .Values.config.mail.from }}
  mail_smtp_host: {{ .Values.config.mail.smtp.host }}
  mail_smtp_username: {{ .Values.config.mail.smtp.username }}
  mail_smtp_port: {{ .Values.config.mail.smtp.port | quote }}
  jitsi_enabled: {{ .Values.config.jitsi.enabled | quote }}
  jitsi_domain: {{ .Values.config.jitsi.domain }}
  jitsi_url_room_prefix: {{ .Values.config.jitsi.url_room_prefix }}
  jitsi_open_new_window: {{ .Values.config.jitsi.open_new_window | quote }}
  jitsi_enable_channels: {{ .Values.config.jitsi.enable_channels | quote }}
  jitsi_chrome_extension: {{ .Values.config.jitsi.chrome_extension }}
  webrtc_enable_channel: {{ .Values.config.webrtc.enable_channel | quote }}
  webrtc_enable_private: {{ .Values.config.webrtc.enable_private | quote }}
  webrtc_enable_direct: {{ .Values.config.webrtc.enable_direct | quote }}
