apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab-runner.fullname" . }}-gitlab-runner
  labels:
    app: {{ template "gitlab-runner.name" . }}-gitlab-runner
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: container
  selector:
    app: {{ template "gitlab-runner.name" . }}-gitlab-runner
    release: {{ .Release.Name }}
