{{- if .Values.ingress.enabled }}
{{- if (and .Values.config.jitsi.enabled (not .Values.config.jitsi.domain)) }}
{{- range .Values.ingress.hosts.jitsi }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "rocketchat.fullname" $ }}-jitsi
  {{- if (and $.Values.ingress.enabled $.Values.ingress.tls) }}
  annotations:
    certmanager.k8s.io/cluster-issuer: {{ $.Values.ingress.issuer.name }}
    kubernetes.io/tls-acme: 'true'
  {{- end }}
  labels:
    app: {{ template "rocketchat.name" $ }}-jitsi
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  rules:
    - host: {{ .name }}
      http:
        paths:
          - path: {{ .path }}
            backend:
              serviceName: {{ template "rocketchat.fullname" $ }}-jitsi
              servicePort: http
  {{- if (and $.Values.ingress.enabled $.Values.ingress.tls) }}
  tls:
    - secretName: letsencrypt-staging
      hosts:
        - {{ .name }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
