apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "wikijs.fullname" . }}
  labels:
    app: {{ template "wikijs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  email: {{ .Values.config.email | quote }}
  mongo_database: {{ .Values.config.mongo.database | quote }}
